enableDebugLogging = false
enableLootUpdateCheck = true
game = 'auto'
language = 'en'
lastGame = 'FalloutNV'
lastVersion = '0.26.0'
preludeSource = 'https://raw.githubusercontent.com/loot/prelude/v0.26/prelude.yaml'
theme = 'default'
updateMasterlist = true
useNoSortingChangesDialog = true
warnOnCaseSensitiveGamePaths = true

[filters]
hideAllPluginMessages = false
hideBashTags = true
hideCRCs = false
hideCreationClubPlugins = false
hideInactivePlugins = false
hideLocations = true
hideMessagelessPlugins = false
hideNotes = false
hideOfficialPluginsCleaningMessages = false
hideVersionNumbers = false
showOnlyEmptyPlugins = false

[groupsEditorWindow]
bottom = 30
left = 0
maximised = false
right = 100
top = 0

[window]
bottom = 1080
left = 768
maximised = true
right = 1792
top = 312

[[games]]
folder = 'FalloutNV'
gameId = 'FalloutNV'
local_path = ''
master = 'FalloutNV.esm'
masterlistSource = 'https://raw.githubusercontent.com/loot/falloutnv/v0.26/masterlist.yaml'
minimumHeaderVersion = 1.3200000524520874
name = 'Fallout: New Vegas'
path = 'C:\Program Files (x86)\Steam\steamapps\common\Fallout New Vegas'

[[languages]]
locale = 'en'
name = 'English'

[[languages]]
locale = 'bg'
name = 'Български'

[[languages]]
locale = 'cs'
name = 'Čeština'

[[languages]]
locale = 'da'
name = 'Dansk'

[[languages]]
locale = 'de'
name = 'Deutsch'

[[languages]]
locale = 'es'
name = 'Español'

[[languages]]
locale = 'fi'
name = 'Suomi'

[[languages]]
locale = 'fr'
name = 'Français'

[[languages]]
locale = 'it'
name = 'Italiano'

[[languages]]
locale = 'ja'
name = '日本語'

[[languages]]
locale = 'ko'
name = '한국어'

[[languages]]
locale = 'pl'
name = 'Polski'

[[languages]]
locale = 'pt_BR'
name = 'Português do Brasil'

[[languages]]
locale = 'pt_PT'
name = 'Português de Portugal'

[[languages]]
locale = 'ru'
name = 'Русский'

[[languages]]
locale = 'sv'
name = 'Svenska'

[[languages]]
locale = 'ta'
name = 'தமிழ்'

[[languages]]
locale = 'tr_TR'
name = 'Türkçe'

[[languages]]
locale = 'uk_UA'
name = 'Українська'

[[languages]]
locale = 'zh_CN'
name = '简体中文'